### ISSUE TITLE
Train model error

### ISSUE THREAD

**Issue by ztl-35** [nusnlp/amanda#7]
Hi
I am trying to train this model,program find a **IndexError** error.i find the (**dot_axes**) argument is probably a error.**i reduce the train data set to 10000 qas.**
Could you tell me how to solve this problem?

Traceback (most recent call last):
  File "src/test_newsqa.py", line 235, in <module>
    model = G.create_model_graph()
  File "../amanda/model.py", line 148, in create_model_graph
    mode='dot', dot_axes=(2, 3))
  File "build/bdist.linux-x86_64/egg/keras/legacy/layers.py", line 465, in merge
  File "build/bdist.linux-x86_64/egg/keras/legacy/layers.py", line 118, in __init__
  File "build/bdist.linux-x86_64/egg/keras/legacy/layers.py", line 184, in _arguments_validation
IndexError: tuple index out of range

**Comment by ztl-35** [comment]
Thanks.i solve it now.i change the model.py.
